# NORMALIZATION PROBLEM

In [11]:
import numpy as np
#accessing functions from the numpy library and calling it as np

X = np.random.random((5,5))
#creating a 5x5 array with random values using the random function 
z = np.mean(X)
#calculating the average of all the values using np.mean()
v = np.std(X)
#calculating the standard deviation using np.std()

normalized = (X-z)/v
#calculating the normalized data by deducting the mean from the X array and dividing by the standard deviation

np.save('X_normalized', normalized)
#saving the normalized array into an .npy file called 'X_normalized'

Normalized_Data = np.load('X_normalized.npy')
#reads the data in 'X.normalized.npy', loads and saves it to 'Normalized_Data'

print(Normalized_Data)
#printing the result saved on 'Normalized_Data'

[[-1.1610477   0.70346215  1.01847981 -0.679209   -1.36375059]
 [-0.76735817 -0.4455238  -0.92108377 -1.18635647  1.33934115]
 [-0.65905722 -0.94352215 -0.08403039 -0.28637402  1.53755347]
 [-0.44675752  0.88204715  1.51933697  1.27814766 -0.17292724]
 [ 0.04630833  1.91086532 -1.25983921 -0.63065696  0.77195221]]


In [44]:
Normalized_Data = np.load('X_normalized.npy')
print(Normalized_Data)

[[-1.1610477   0.70346215  1.01847981 -0.679209   -1.36375059]
 [-0.76735817 -0.4455238  -0.92108377 -1.18635647  1.33934115]
 [-0.65905722 -0.94352215 -0.08403039 -0.28637402  1.53755347]
 [-0.44675752  0.88204715  1.51933697  1.27814766 -0.17292724]
 [ 0.04630833  1.91086532 -1.25983921 -0.63065696  0.77195221]]


##### Normalized data was saved in X_normalized.npy and was printed

# DIVISIBLE BY 3 PROBLEM

In [47]:
import numpy as nd
#accessing the numpy library and calling it as nd

w = nd.arange(1,101,1)
#creating a 1d array containing the numbers 1-100 by starting the array by 1, 
#incrementing by 1 up to 100 excluding the terminal value 101
#data is stored in w
y = nd.arange(1,101,1)
#creating another 1d array with the same elements as array w
n = w * y
#element-wise multiplication of the array w and array y to get their squares
#storing the data in n
j = n.reshape(10,10)
#reshaping the data in n into a 10x10 array and storing it in j
print(j)
#printing the reshaped array j


print("\nThe numbers divisible by 3 are:")
#label for the list of the numbers divisible by 3)
divisible = [] 
#making a list named 'divisible' to store the numbers divisible by 3
for k in n:
#a for loop to check for divisibility for each element in n
    if k % 3 == 0:
    #determining if the value of k is divisible by 3 through modulo
        divisible.append(k)
        #adding the last element divisible by 3 to the list
        
nd.save('div_by_3', divisible)
#saving the values within the list divisible as a .npy file named 'div_by_3'
b = nd.load('div_by_3.npy')
#reading the .npy file, loading it and storing it into b
print(b)
#print the values in b

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

The numbers divisible by 3 are:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [45]:
b = nd.load('div_by_3.npy')
print(b)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


##### All the elements divisible by 3 was saved in div_by_3 and was printed