# NORMALIZATION PROBLEM

In [2]:
import numpy as nd
#accessing functions from the numpy library and calling it as nd

X = nd.random.random((5,5))
#creating a 5x5 array with random values using the random function 
z = nd.mean(X)
#calculating the mean of the values using the pre-defined mean function
v = nd.std(X)
#calculating the mean of the values inside the array using the pre-defined 
#standard function

normalized = (X-z)/v
#calculating the normalized data by deducting the mean from the X array and 
#dividing by the standard deviation

nd.save('X_normalized', normalized)

loaded_normalized = nd.load('X_normalized.npy')
print(loaded_normalized)

[[-1.36338287  0.28578382  1.12659304  0.463112    0.55458296]
 [-1.60588896 -0.65459582 -0.98951269  0.90394311  0.69962455]
 [-1.59957882  1.42090786  1.46621712 -1.37934267  0.67422006]
 [ 0.69718449 -1.29627457  0.66870227  0.48141319  0.66711134]
 [-0.11375537  0.26279272 -0.74966313  0.86547084 -1.48566449]]


# DIVISIBLE BY 3 PROBLEM

In [9]:
import numpy as nd

w = nd.arange(1,101,1)
p = nd.arange(1,101,1)
n = w*p
j = n.reshape(10,10)
print(j)

print('The numbers divisible by 3 are:')
for k in n:
    if k%3 == 0:
        print(k)

nd.save('div_by_3', k)

loaded_k = nd.load('div_by_3.npy')
print(loaded_k)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
The numbers divisible by 3 are:
9
36
81
144
225
324
441
576
729
900
1089
1296
1521
1764
2025
2304
2601
2916
3249
3600
3969
4356
4761
5184
5625
6084
6561
7056
7569
8100
8649
9216
9801
10000
